// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQbmoYADkvntDxgYsfFk4d-42LlzDYA4',
    appId: '1:363047723402:web:0ea69c46330b062a896873',
    messagingSenderId: '363047723402',
    projectId: 'cloudapp-7c4db',
    authDomain: 'cloudapp-7c4db.firebaseapp.com',
    storageBucket: 'cloudapp-7c4db.firebasestorage.app',
    measurementId: 'G-VW72P02TXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZyOmac2GSZTHCqpf_ppDywNdexo74UA',
    appId: '1:363047723402:android:e3f6ccb83b35c24a896873',
    messagingSenderId: '363047723402',
    projectId: 'cloudapp-7c4db',
    storageBucket: 'cloudapp-7c4db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuGJzF3cs5ucW-w2UJXAssHi2aTMKhLc',
    appId: '1:363047723402:ios:3278d712b369f0e8896873',
    messagingSenderId: '363047723402',
    projectId: 'cloudapp-7c4db',
    storageBucket: 'cloudapp-7c4db.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

}